version: '3.8'
services:
  redis:
    image: redis:7.2-rc2
    restart: always
    ports:
      - 6379:6379
    command: redis-server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cryptex
      POSTGRES_PASSWORD: cryptex
      POSTGRES_DB: cryptex
    ports:
      - '5432:5432'
